/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  /*
  NeigeItems: [
    'README',
  ],
   */
};

module.exports = sidebars;
