name: Workflow Build
on:
  push:
    branches:
      - main
jobs:
  # 自动生成PDF
  pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Build PDF
      run: |
        docker run --rm -v $(pwd)/pdf:/app/pdf openbayes/docusaurus-prince-pdf bash
        curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
        tar zxf prince-14.2-linux-generic-x86_64.tar.gz
        cd prince-14.2-linux-generic-x86_64
        sudo ./install.sh
        docker run --rm -v $(pwd)/pdf:/app/pdf openbayes/docusaurus-prince-pdf -u https://docusaurus.io/docs/
#     # 生成PDF
#     - name: Build PDF
#       run: sudo docker run --rm -it -v $(pwd)/pdf:/app/pdf openbayes/docusaurus-prince-pdf -u https://neige7.github.io/NeigeItems-Wiki-Docusaurus/intro --output pdf/NeigeItems-Wiki.pdf
#     # 生成英文PDF
#     - name: Build PDF
#       run: sudo docker run --rm -it -v $(pwd)/pdf:/app/pdf openbayes/docusaurus-prince-pdf -u https://neige7.github.io/NeigeItems-Wiki-Docusaurus/en/intro --output pdf/NeigeItems-Wiki-English.pdf
#     # 上传PDF
#     - name: Capture Build Artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: Artifacts
#         path: pdf/
#         if-no-files-found: error

#   test:
#     runs-on: windows-latest
#     steps:
#     - name: test1
#       run: |
#         ping baidu.com
#         ping neige7.github.io
#     - name: Checkout
#       uses: actions/checkout@master
#       with:
#         persist-credentials: false
#     # 设置Prince环境变量
#     - name: Setup Windows path
#       uses: myci-actions/append-to-path-windows@2
#       with:
#         path: ${{ github.workspace }}\prince-15.1-win64\bin
#         env-var: Path
#     - name: test
#       run: |
#         npx docusaurus-prince-pdf -u https://neige7.github.io/NeigeItems-Wiki-Docusaurus/intro --output pdf/NeigeItems-Wiki.pdf
#         npx docusaurus-prince-pdf -u https://neige7.github.io/NeigeItems-Wiki-Docusaurus/en/intro --output pdf/NeigeItems-Wiki-English.pdf
#     # 上传PDF
#     - name: Capture Build Artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: Artifacts
#         path: pdf/
#         if-no-files-found: error
#   # 自动部署GitPage
#   gitpage:
#     runs-on: ubuntu-latest
#     steps:
#     # 拉取代码
#     - name: Checkout
#       uses: actions/checkout@master
#       with:
#         persist-credentials: false
#     # 编译出静态页面
#     - name: Install and Build
#       run: npm install && npm run build
#     # 塞进gh-pages分支(即部署到GitPage)
#     - name: Deploy
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: build
#   # 自动生成PDF
#   pdf:
#     needs: [ gitpage ]
#     runs-on: windows-latest
#     steps:
#     # 拉取代码
#     - name: Checkout
#       uses: actions/checkout@master
#       with:
#         persist-credentials: false
#     # 设置Prince环境变量
#     - name: Setup Windows path
#       uses: myci-actions/append-to-path-windows@2
#       with:
#         path: ${{ github.workspace }}\prince-15.1-win64\bin
#         env-var: Path
#     # 睡会儿, 等GitPage部署完成
#     - name: Sleep for 120 seconds
#       run: Start-Sleep -s 30
#       shell: powershell
#     # 生成PDF
#     - name: Build PDF
#       run: npx docusaurus-prince-pdf -u https://neige7.github.io/NeigeItems-Wiki-Docusaurus/intro --output pdf/NeigeItems-Wiki.pdf
#     # 生成英文PDF
#     - name: Build English PDF
#       run: npx docusaurus-prince-pdf -u https://neige7.github.io/NeigeItems-Wiki-Docusaurus/en/intro --output pdf/NeigeItems-Wiki-English.pdf
#     # 上传PDF
#     - name: Capture Build Artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: Artifacts
#         path: pdf/
#         if-no-files-found: error
#   # Release
#   release:
#     needs: [ pdf ]
#     runs-on: ubuntu-latest
#     steps:
#     # 拉取代码
#     - name: Checkout Repository
#       uses: actions/checkout@v2
#     # 下载本体
#     - name: Download Content
#       uses: actions/download-artifact@v2
#       with:
#         name: Artifacts
#     # 获取序号
#     - name: Get Project version
#       id: get_version
#       run: |
#         echo "Project version: $GITHUB_RUN_NUMBER"
#         echo "::set-output name=project_version::$GITHUB_RUN_NUMBER"
#       env:
#         project_version: ${{ steps.get_version.outputs.project_version }}
#     # 创建release
#     - name: Create Release
#       id: create-new-release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ steps.get_version.outputs.project_version }}
#         release_name: Auto Release ${{ steps.get_version.outputs.project_version }}
#     # 向release上传NeigeItems-Wiki.pdf
#     - name: Upload PDF file to Release
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create-new-release.outputs.upload_url }}
#         asset_path: NeigeItems-Wiki.pdf
#         asset_name: NeigeItems-Wiki.pdf
#         asset_content_type: application/zip
#     # 向release上传NeigeItems-Wiki-English.pdf
#     - name: Upload PDF file to Release
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create-new-release.outputs.upload_url }}
#         asset_path: NeigeItems-Wiki-English.pdf
#         asset_name: NeigeItems-Wiki-English.pdf
#         asset_content_type: application/zip
